### ISSUE TITLE
In fact, this is an issue, but a comment.

### ISSUE THREAD

**Issue by wangtao13** [dpw/kvm-hello-world#1]
This code is very very helpful for the one just beginning to learn to KVM, thanks for the excellent job.
I just finished testing the MMIO emulation based on your code (changed your code to support KVM_MMIO_EXIT).

And I would like to see your code to have more and more features to show the features/functionalities of KVM.

And here is another example in github for KVM API for your reference.
https://github.com/hitmoon/kvmsample/blob/master/main.c.

**Comment by dpw** [comment]
Thanks for the comment!  I'm glad to hear you are finding this useful.

And thanks for letting me know about that kvmsample project.  I did search for similar projects, but didn't find anything.  Maybe I didn't look hard enough.  I'll add a link to the README.

**Comment by dpw** [comment]
I've added a link to kvmsample to the README.  Thanks again!
