### ISSUE TITLE
Undefined Reference to "_GLOBAL_OFFSET_TABLE_" when linking guest32.o

### ISSUE THREAD

**Issue by AnonymousII** [dpw/kvm-hello-world#4]
Hi,

first of all thanks a lot for all the code, I'm currently trying to get started setting up a VM with KVM api (ideally 64 bit mode later on) and these examples help me a lot in understanding how to use the KVM api :+1: 

Unfortunately I get an error message When trying to compile the code with "make run":

_______________
Original Output:
ld -T guest.ld -m elf_i386 guest32.o -o guest32.img
guest32.o: In Funktion »_start«:
guest.c:(.start+0x6): Warnung: undefinierter Verweis auf »_GLOBAL_OFFSET_TABLE_«
Makefile:26: die Regel für Ziel „guest32.img“ scheiterte
make: *** [guest32.img] Fehler 1
_______________

So ld complains about an undefined reference to "_GLOBAL_OFFSET_TABLE_" at offset ".start+0x6" when trying to link the guest32.o file into guest32.img using the guest.ld linker script.
(Trying to build this on an Ubuntu 17.10 64 bit OS with Intel® Core™ i5-2400 CPU inside).

Anyway 16bit and 64bit version give no errors when compiling and linking, everything works just fine here.

Did I miss anything for 32bit-mode? Unfortunately I don't have an idea how to fix this problem currently ...
Could you maybe tell me what causes this problem and how to fix it?

Thanks a lot in advance for your help :)

Kind regards,
Andreas

**Comment by dpw** [comment]
I'm not sure what the problem is.  It doesn't sound like you are doing anything wrong.  I'll try installing Ubuntu 17.10 in a VM and see if I can reproduce the problem.  I hope to do that in the next few days.

**Comment by dpw** [comment]
I couldn't get nested KVM working within a VM, so I reproduced the problem by using debootstrap to build an Ubuntu 17.10 chroot.

The error is due to recent versions of Ubuntu building PIE/PIC by default (https://wiki.ubuntu.com/SecurityTeam/PIE).  I've added the -fno-pic option to the relevant gcc lines in the Makefile to prevent this.  It should work for you now.
