### ISSUE TITLE
64 bit mode broken in Ubuntu 18.04 LTS (KVM_SET_SREGS: Invalid argument)

### ISSUE THREAD

**Issue by AnonymousII** [dpw/kvm-hello-world#5]
Hi,

since Ubuntu 18.04 LTS came out 2 days ago I performed a clean install of Ubuntu 18.04 LTS 64 bit.
Unfortunately in the latest Ubuntu Version the Long Mode Version seems broken:
`ioctl(vcpu->fd, KVM_SET_SREGS, &sregs)` (run_long_mode() line 410 kvm-hello-world.c) fails with:
> KVM_SET_SREGS: Invalid argument

All other Modes (16 bit, 32 bit, 32 bit paged) still work fine. Also reinstalling the old Version Ubuntu 17.10 64 bit makes the problem disappear, so it must be related to a change in the KVM module in the latest Ubuntu version.

Taking a closer look at the Code shows that 32 bit Paged Mode and 64 bit Mode Settings only differ in 4 Points:

-Segment Setup: 
--seg.db=1 in 32 bit (=> default operand size 32 bit), =0 in 64 bit (=> 16 bit Operand Size)
--seg.l=0 in 32 bit, =1 in 64 bit (=1 enables 64 bit instruction encoding)
-Control Register Setup:
--CR4=CR4_PSE in 32 bit (4 MiB Pages), =CR4_PAE (36 bit extended physical address translation in gpt)
--EFER=0 in 32 bit, =EFER_LME in 64 bit (long mode enable)

Experimenting a bit shows that the problem is probably related to the combination of seg.l=1 and EFER=EFER_LME: when both are reset to the 32 bit settings the problem seems to disappear (to be precise it causes another problem resulting in a KVM_EXIT_SHUTDOWN but it makes the error "KVM_SET_SREGS: Invalid argument" disappear and lets the VM start).

Anyway seg.l=1 and EFER=EFER_LME are essential for entering 64 bit mode and can't be skipped of course - Maybe there was a change in Ubuntu 18.04 KVM regarding long mode in virtual machines? At least I didn't read about any such change...

Could you maybe tell me how to fix this problem?

Thanks a lot in advance for your help :)

Kind regards,
Andreas

**Comment by AnonymousII** [comment]
**Update (fixed):** After some further experiments I'm pretty sure to have fixed the problem:
In the EFER-Control Register the bit EFER_LMA = (1U << 10) (=Long Mode Active, see [https://en.wikipedia.org/wiki/Control_register#EFER](url)) needs to be set.

Obviously the old KVM version did not check for "Long Mode Active" to be set and was satisfied with "Long Mode Enable".
So Adding the following line of code to kvm-hello-world.c:setup_long_mode() obviously fixes the problem:
`sregs->efer |= (1U << 10);//EFER_LMA`

Would be cool if you could patch the code so that it works on the latest Ubuntu version in case others run into the same problem :)

Anyway I don't understand why there's two different flags "enable" and "active" for long mode:
Why would it make sense to enable but not activate long mode or to activate long mode without it being enabled? I'm a bit confused why there's two different control bits here... Can you maybe tell me why there's two "different" flags for long mode?

Kind regards,
Andreas

**Comment by justinc1** [comment]
The 64 bit code crashed on Fedora 27 too. The patch from @AnonymousII helped. I took liberty to send pull request (but it has wrong signed off header).

**Comment by dpw** [comment]
Thanks.  Sorry it took a while for me to merge the fix - I needed to reinstall a machine at home to test.
